name: Ethlint-Linter-CI
on: [push]
jobs:
  solhint:
    name: Run the solhint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run linter - Ethlint
        shell: pwsh
        run: |
          .\sample.ps1
