name: Linter-CI
on: [push]
jobs:
  solhint:
    name: Run the solhint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run solhint with contracthsark
        uses: contractshark/inject-solhint-ci@1.0.0+0
        with:
            github_token: ${{ secrets.GITHUBTOKEN }}
            reporter: github-pr-review # Change reporter.
            solhint_input: 'contracts/*.sol'
