name: solhint-ci
on: [push]
jobs:
  solhint:
    name: runner / solhint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run solhint with contracthsark
        uses: contractshark/inject-solhint-ci@1.0.0+0
        with:
            solhint_input: '.sol'
#           github_token: ${{ secrets.github_token }}
#           reporter: github-pr-review # Change reporter.
#           VALIDATE_ALL_CODEBASE: true
#           DEFAULT_BRANCH: main
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
