name: Linter-CI
on: [push]
jobs:
  solhint:
    name: Run the solhint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run solhint with contracthsark
        run: .\sample.ps1
